name: Docker Image

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false

      - name: Setup cargo binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install watchexec from crates.io
        run: |
          cargo binstall watchexec-cli --target x86_64-unknown-linux-musl
          which watchexec
          ldd $(which watchexec)
          cp $(which watchexec) ./

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: |
          go env -w GO111MODULE=on
          make build-static

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Bedrock-Technology
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/bedrock-technology/lambda:latest,ghcr.io/bedrock-technology/lambda:${{ steps.tag.outputs.tag }}
